services:

  proxy:
    image: traefik:3.2
    command: --api.insecure=true --providers.docker
    restart: unless-stopped
    ports:
      - 8001:80
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    image: andreanidouglas/weather-dashboard-api:latest
    environment:
      - STANDALONE=false
      - API_KEY=<enter your api key>
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.be.rule=Host(`weather.local`)"
      - "traefik.http.routers.be.rule=PathPrefix(`/api`)"
      - "traefik.http.services.be.loadbalancer.server.port=8080"

  frontend:
    image: andreanidouglas/weather-dashboard-frontend:latest
    volumes:
      - ./view/src:/var/www/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fe.rule=Host(`weather.local`)"
      - "traefik.http.services.fe.loadbalancer.server.port=80"
      - "traefik.http.routers.fe.rule=!PathPrefix(`/api`)"
